import type { PlayerProfile } from "@/types";

export const player: PlayerProfile = {
  name: "Abdul Ahad Omer",
  brand: "Abdul Ahad Omer | @10",
  shirtNumber: 10,
  tagline: "Vision. Tempo. Decision.",
  bio: "Creative attacking midfielder with a relentless work rate and a playmaker's mind. Known for breaking lines with first-touch passing, decisive movement between the lines, and clutch performances in the final third. Driven to compete at the highest level of professional football.",
  age: 17,
  dob: "2008-05-12",
  nationality: "Pakistani",
  city: "Lahore, Pakistan",
  height: "1.78 m",
  weight: "68 kg",
  foot: "Right",
  position: "Attacking Midfielder",
  secondaryPositions: ["Central Midfielder", "Winger"],
  currentClub: "Independent — Open to academy / pro trial",
  agentRepresented: false,
  availability: "Open to trials, academy placements, and showcase tournaments",
  languages: ["English", "Urdu", "Punjabi"],
  socials: {
    instagram: "https://instagram.com/abdulahadomer.10",
    youtube: "https://youtube.com/@abdulahadomer10",
    tiktok: "https://tiktok.com/@abdulahadomer.10",
    email: "contact@abdulahadomer.com",
  },
  strengths: [
    "Line-breaking passing",
    "Press resistance under pressure",
    "Off-ball intelligence",
    "Two-footed finishing",
    "Set-piece delivery",
    "Leadership & on-pitch communication",
  ],
  developmentFocus: [
    "Aerial duels & physicality",
    "Defensive transitions",
    "Tactical periodisation in pro environments",
    "Strength & conditioning under pro load",
  ],
  achievements: [
    "U-16 Regional League — Top Assists (12)",
    "Captain — School First XI for 2 seasons",
    "Selected for inter-city development squad (2024)",
    "MVP — Youth Cup Showcase 2024",
    "100+ goal involvements across age-grade football",
  ],
};
